/**
 * rfc-0039-style stream receipts (issue #84, rolling-swap spec §7.2).
 *
 * Per fulfilled packet the maker attaches a compact SIGNED receipt to the
 * FULFILL accept-metadata: a monotone cumulative proof of asset-B delivered
 * in the session. The receipt chain is the sender's portable audit/dispute
 * artifact today (it makes the maker-debt bound provable to a third party)
 * and the natural input to a future escrow layer. Receipts are
 * session-scoped via `streamNonce`; the latest receipt supersedes all
 * earlier ones, mirroring the highest-nonce rule for claims.
 *
 * ## Deviations from Interledger rfc-0039 (documented per spec §7.2 — the
 * TOON-native equivalent deliberately does not import the STREAM framing):
 *
 * - **Signature, not HMAC.** rfc-0039 authenticates receipts with
 *   HMAC-SHA256 over a pre-shared 32-byte Receipt Secret, so only a party
 *   holding the secret can verify. TOON receipts are BIP-340 Schnorr
 *   signatures by the maker's receipt key (default: the maker's Nostr
 *   identity key — the same `swapPubkey` the sender already discovered via
 *   kind:10032), making every receipt verifiable by ANY third party with
 *   the maker's pubkey. No Receipt Secret exists or is provisioned.
 * - **Nonce provisioning.** rfc-0039's Verifier generates the Receipt Nonce
 *   and communicates it out-of-band (SPSP headers). Here the sender (who is
 *   its own verifier today) generates a 16-byte `streamNonce` per
 *   `streamSwap()` invocation and communicates it in-band as the rumor's
 *   `stream-nonce` tag. Legacy makers ignore the unknown tag.
 * - **Encoding.** JSON object inside the accept-metadata dict rather than a
 *   CANONICAL-OER STREAM frame. A deterministic length-prefixed binary
 *   encoding ({@link encodeReceiptSigningPayload}) is used ONLY as the
 *   signing preimage.
 * - **Fields.** `seq` (maker's per-session fulfill counter — enables hole
 *   detection, absent from rfc-0039), `rate` + `rateTimestamp` (the quote
 *   tape entry, attested under the maker signature) are added; the STREAM
 *   `Stream ID` is dropped (one logical stream per session — the
 *   `streamNonce` IS the stream identity); `Total Received` is a decimal
 *   string (bigint range) rather than UInt64.
 *
 * rfc-0039 semantics preserved: one receipt per fulfilled packet, each
 * carrying a progressively higher cumulative total; latest supersedes;
 * verification = authenticity check + monotonicity against previously seen
 * receipts for the same nonce.
 *
 * @module
 */

import { schnorr } from '@noble/curves/secp256k1.js';
import { sha256 } from '@noble/hashes/sha2.js';
import { bytesToHex, hexToBytes } from '@noble/hashes/utils.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Wire version of the TOON stream receipt. */
export const STREAM_RECEIPT_VERSION = 1 as const;

/** Domain-separation tag prefixed to the receipt signing payload. */
export const STREAM_RECEIPT_SIGNING_TAG = 'toon.stream-receipt.v1';

/** The signed fields of a {@link StreamReceipt} (everything except `sig`). */
export interface StreamReceiptFields {
  /** Receipt wire version — always {@link STREAM_RECEIPT_VERSION}. */
  v: typeof STREAM_RECEIPT_VERSION;
  /**
   * Session identifier: 32-char lowercase hex (16 bytes), generated by the
   * sender per stream and echoed by the maker on every receipt.
   */
  streamNonce: string;
  /**
   * Maker's per-session fulfill counter, 1-based, strictly increasing by 1
   * per fulfilled packet. Gaps observed by the sender indicate receipts it
   * never received (hole detection).
   */
  seq: number;
  /**
   * Running total of asset B delivered in this session (target micro-units,
   * decimal string). Monotone non-decreasing in `seq`; the latest receipt
   * supersedes all earlier ones.
   */
  cumulativeDelivered: string;
  /** The maker's quote `R_i` applied to the packet this receipt rode on (decimal string). */
  rate: string;
  /** Unix ms timestamp when the maker's rate source produced {@link rate}. */
  rateTimestamp: number;
}

/**
 * A signed stream receipt as carried on the FULFILL accept-metadata under
 * the `receipt` key (rolling-swap spec §7.2).
 */
export interface StreamReceipt extends StreamReceiptFields {
  /**
   * 128-char lowercase hex BIP-340 Schnorr signature by the maker's receipt
   * key over `sha256(encodeReceiptSigningPayload(fields))`.
   */
  sig: string;
}

/**
 * Aggregate view of the receipts harvested from one stream — the serialized
 * audit/dispute artifact's in-memory shape. Returned on
 * `StreamSwapResult.receipts` (present on abort too, covering what filled).
 */
export interface StreamReceiptChain {
  /** The sender-generated session nonce receipts were verified against. */
  streamNonce: string;
  /** All verified receipts, sorted by ascending `seq`. */
  receipts: StreamReceipt[];
  /** Highest-`seq` receipt — supersedes all others (rfc-0039 latest-wins). */
  latest?: StreamReceipt;
  /**
   * `latest.cumulativeDelivered`, or `'0'` when no receipt was received —
   * the signed total of asset B the maker attests to having delivered.
   */
  totalDelivered: string;
  /**
   * Missing `seq` values in `[1, latest.seq]`: fulfilled packets whose
   * receipts the sender never received (lost FULFILLs, or maker skips).
   */
  holes: number[];
}

// ---------------------------------------------------------------------------
// Validation helpers
// ---------------------------------------------------------------------------

const STREAM_NONCE_REGEX = /^[0-9a-f]{32}$/;
const SIG_REGEX = /^[0-9a-f]{128}$/;
const HEX64_REGEX = /^[0-9a-f]{64}$/;
const DECIMAL_UINT_REGEX = /^(0|[1-9]\d*)$/;
const RATE_REGEX = /^(0|[1-9]\d*)(\.\d+)?$/;

/** True iff `value` is a well-formed 32-char lowercase hex stream nonce. */
export function isValidStreamNonce(value: unknown): value is string {
  return typeof value === 'string' && STREAM_NONCE_REGEX.test(value);
}

/**
 * Structurally validate an untrusted metadata `receipt` value into a
 * {@link StreamReceipt}. Checks shape ONLY — no signature or monotonicity
 * verification (that is {@link verifyStreamReceipt} / {@link ReceiptChainTracker}).
 *
 * @throws {Error} with a human-readable reason when malformed. Callers
 *   (e.g. `decodeFulfillMetadata`) wrap into their own error taxonomy.
 */
export function parseStreamReceipt(value: unknown): StreamReceipt {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error('receipt must be an object');
  }
  const obj = value as Record<string, unknown>;
  if (obj['v'] !== STREAM_RECEIPT_VERSION) {
    throw new Error(
      `receipt.v must be ${STREAM_RECEIPT_VERSION}, got ${String(obj['v'])}`
    );
  }
  if (!isValidStreamNonce(obj['streamNonce'])) {
    throw new Error('receipt.streamNonce must be 32-char lowercase hex');
  }
  const seq = obj['seq'];
  if (typeof seq !== 'number' || !Number.isSafeInteger(seq) || seq < 1) {
    throw new Error('receipt.seq must be a positive safe integer');
  }
  const cumulativeDelivered = obj['cumulativeDelivered'];
  if (
    typeof cumulativeDelivered !== 'string' ||
    !DECIMAL_UINT_REGEX.test(cumulativeDelivered)
  ) {
    throw new Error(
      'receipt.cumulativeDelivered must be a non-negative integer decimal string'
    );
  }
  const rate = obj['rate'];
  if (
    typeof rate !== 'string' ||
    !RATE_REGEX.test(rate) ||
    /^0(\.0+)?$/.test(rate)
  ) {
    throw new Error('receipt.rate must be a positive decimal string');
  }
  const rateTimestamp = obj['rateTimestamp'];
  if (
    typeof rateTimestamp !== 'number' ||
    !Number.isInteger(rateTimestamp) ||
    rateTimestamp <= 0
  ) {
    throw new Error(
      'receipt.rateTimestamp must be a positive integer (unix ms)'
    );
  }
  const sig = obj['sig'];
  if (typeof sig !== 'string' || !SIG_REGEX.test(sig)) {
    throw new Error('receipt.sig must be 128-char lowercase hex');
  }
  return {
    v: STREAM_RECEIPT_VERSION,
    streamNonce: obj['streamNonce'] as string,
    seq,
    cumulativeDelivered,
    rate,
    rateTimestamp,
    sig,
  };
}

// ---------------------------------------------------------------------------
// Canonical signing payload + sign/verify
// ---------------------------------------------------------------------------

/**
 * Deterministic binary encoding of the signed receipt fields — the signing
 * preimage. Layout (all integers big-endian):
 *
 * ```
 * len(tag):u32 || tag(utf8) || v:u8 || streamNonce(16 raw bytes)
 *   || seq:u64 || len:u32 || cumulativeDelivered(utf8)
 *   || len:u32 || rate(utf8) || rateTimestamp:u64
 * ```
 *
 * Length prefixes remove concatenation ambiguity between the variable-width
 * decimal strings (same rationale as the swap-handler replay packet-id hash).
 */
export function encodeReceiptSigningPayload(
  fields: StreamReceiptFields
): Uint8Array {
  if (!isValidStreamNonce(fields.streamNonce)) {
    throw new Error('streamNonce must be 32-char lowercase hex');
  }
  const tag = Buffer.from(STREAM_RECEIPT_SIGNING_TAG, 'utf8');
  const cumulative = Buffer.from(fields.cumulativeDelivered, 'utf8');
  const rate = Buffer.from(fields.rate, 'utf8');
  const buf = Buffer.alloc(
    4 + tag.length + 1 + 16 + 8 + 4 + cumulative.length + 4 + rate.length + 8
  );
  let off = 0;
  buf.writeUInt32BE(tag.length, off);
  off += 4;
  tag.copy(buf, off);
  off += tag.length;
  buf.writeUInt8(fields.v, off);
  off += 1;
  Buffer.from(hexToBytes(fields.streamNonce)).copy(buf, off);
  off += 16;
  buf.writeBigUInt64BE(BigInt(fields.seq), off);
  off += 8;
  buf.writeUInt32BE(cumulative.length, off);
  off += 4;
  cumulative.copy(buf, off);
  off += cumulative.length;
  buf.writeUInt32BE(rate.length, off);
  off += 4;
  rate.copy(buf, off);
  off += rate.length;
  buf.writeBigUInt64BE(BigInt(fields.rateTimestamp), off);
  return new Uint8Array(buf);
}

/**
 * Sign the receipt fields with the maker's receipt secret key (32-byte
 * secp256k1 scalar — by default the maker's Nostr identity key). Returns
 * the complete {@link StreamReceipt} with the BIP-340 Schnorr `sig` over
 * `sha256(encodeReceiptSigningPayload(fields))`.
 */
export function signStreamReceipt(
  fields: StreamReceiptFields,
  secretKey: Uint8Array
): StreamReceipt {
  if (!(secretKey instanceof Uint8Array) || secretKey.length !== 32) {
    throw new Error('receipt secretKey must be a 32-byte Uint8Array');
  }
  const digest = sha256(encodeReceiptSigningPayload(fields));
  const sig = bytesToHex(schnorr.sign(digest, secretKey));
  return { ...fields, sig };
}

/**
 * Verify a receipt's Schnorr signature against the maker's receipt pubkey
 * (64-char lowercase hex x-only key — by default the maker's `swapPubkey`).
 * Authenticity only; monotonicity/session checks live in
 * {@link ReceiptChainTracker}.
 */
export function verifyStreamReceipt(
  receipt: StreamReceipt,
  makerPubkey: string
): boolean {
  if (typeof makerPubkey !== 'string' || !HEX64_REGEX.test(makerPubkey)) {
    return false;
  }
  if (typeof receipt.sig !== 'string' || !SIG_REGEX.test(receipt.sig)) {
    return false;
  }
  try {
    const { sig: _sig, ...fields } = receipt;
    const digest = sha256(encodeReceiptSigningPayload(fields));
    return schnorr.verify(
      hexToBytes(receipt.sig),
      digest,
      hexToBytes(makerPubkey)
    );
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------
// Sender-side accumulation — ReceiptChainTracker
// ---------------------------------------------------------------------------

/** Outcome of {@link ReceiptChainTracker.add}. */
export type ReceiptAddResult =
  | { ok: true }
  | {
      ok: false;
      /** Machine-readable rejection reason. */
      code:
        | 'BAD_SIGNATURE'
        | 'WRONG_STREAM_NONCE'
        | 'DUPLICATE_SEQ'
        | 'NON_MONOTONIC';
      message: string;
    };

/**
 * Accumulates and verifies the receipt chain for ONE stream session.
 *
 * Per added receipt it checks, in order:
 * 1. `streamNonce` matches the session (a receipt for another session is
 *    worthless as proof for this one),
 * 2. the Schnorr signature verifies against the maker's receipt pubkey,
 * 3. `seq` is not a duplicate,
 * 4. `cumulativeDelivered` is monotone in `seq` against every receipt seen
 *    so far: non-decreasing with ascending `seq` (rfc-0039 "progressively
 *    higher amount"; non-strict so a zero-target packet — possible under
 *    `applyRate` truncation — does not read as maker equivocation).
 *
 * Receipts may be added OUT OF ORDER (adaptive W>1 streams complete in
 * arbitrary order); monotonicity is enforced against both the nearest lower
 * and nearest higher `seq` neighbors.
 */
export class ReceiptChainTracker {
  readonly #streamNonce: string;
  readonly #makerPubkey: string;
  /** Verified receipts, kept sorted by ascending seq. */
  readonly #receipts: StreamReceipt[] = [];
  readonly #seqs = new Set<number>();

  constructor(input: { streamNonce: string; makerPubkey: string }) {
    if (!isValidStreamNonce(input.streamNonce)) {
      throw new Error('streamNonce must be 32-char lowercase hex');
    }
    if (
      typeof input.makerPubkey !== 'string' ||
      !HEX64_REGEX.test(input.makerPubkey)
    ) {
      throw new Error('makerPubkey must be a 64-char lowercase hex string');
    }
    this.#streamNonce = input.streamNonce;
    this.#makerPubkey = input.makerPubkey;
  }

  get streamNonce(): string {
    return this.#streamNonce;
  }

  /** Number of verified receipts accumulated so far. */
  get size(): number {
    return this.#receipts.length;
  }

  /**
   * Verify + accumulate one receipt. On `{ok: false}` the receipt is NOT
   * added and the chain is unchanged.
   */
  add(receipt: StreamReceipt): ReceiptAddResult {
    if (receipt.streamNonce !== this.#streamNonce) {
      return {
        ok: false,
        code: 'WRONG_STREAM_NONCE',
        message: `receipt streamNonce ${receipt.streamNonce} does not match session ${this.#streamNonce}`,
      };
    }
    if (!verifyStreamReceipt(receipt, this.#makerPubkey)) {
      return {
        ok: false,
        code: 'BAD_SIGNATURE',
        message: `receipt seq ${receipt.seq} signature does not verify against maker key ${this.#makerPubkey}`,
      };
    }
    if (this.#seqs.has(receipt.seq)) {
      return {
        ok: false,
        code: 'DUPLICATE_SEQ',
        message: `duplicate receipt seq ${receipt.seq}`,
      };
    }
    // Binary-search the sorted insert position, then check both neighbors.
    let lo = 0;
    let hi = this.#receipts.length;
    while (lo < hi) {
      const mid = (lo + hi) >>> 1;
      const midReceipt = this.#receipts[mid] as StreamReceipt;
      if (midReceipt.seq < receipt.seq) lo = mid + 1;
      else hi = mid;
    }
    const cumulative = BigInt(receipt.cumulativeDelivered);
    const lower = lo > 0 ? this.#receipts[lo - 1] : undefined;
    const higher = lo < this.#receipts.length ? this.#receipts[lo] : undefined;
    if (lower && BigInt(lower.cumulativeDelivered) > cumulative) {
      return {
        ok: false,
        code: 'NON_MONOTONIC',
        message: `receipt seq ${receipt.seq} cumulativeDelivered ${receipt.cumulativeDelivered} is below seq ${lower.seq}'s ${lower.cumulativeDelivered}`,
      };
    }
    if (higher && BigInt(higher.cumulativeDelivered) < cumulative) {
      return {
        ok: false,
        code: 'NON_MONOTONIC',
        message: `receipt seq ${receipt.seq} cumulativeDelivered ${receipt.cumulativeDelivered} is above seq ${higher.seq}'s ${higher.cumulativeDelivered}`,
      };
    }
    this.#receipts.splice(lo, 0, receipt);
    this.#seqs.add(receipt.seq);
    return { ok: true };
  }

  /**
   * Snapshot the accumulated chain: sorted receipts, the superseding latest,
   * the signed total delivered, and any `seq` holes in `[1, latest.seq]`.
   */
  chain(): StreamReceiptChain {
    const receipts = [...this.#receipts];
    const latest = receipts[receipts.length - 1];
    const holes: number[] = [];
    if (latest) {
      for (let seq = 1; seq <= latest.seq; seq++) {
        if (!this.#seqs.has(seq)) holes.push(seq);
      }
    }
    return {
      streamNonce: this.#streamNonce,
      receipts,
      ...(latest !== undefined && { latest }),
      totalDelivered: latest?.cumulativeDelivered ?? '0',
      holes,
    };
  }
}

/**
 * Serialize a receipt chain into the portable audit/dispute artifact: a
 * stable, versioned JSON document. Any third party holding the maker's
 * receipt pubkey can re-verify every receipt in it offline (the enclosed
 * receipts are self-contained signed statements).
 */
export function serializeReceiptChain(chain: StreamReceiptChain): string {
  return JSON.stringify({
    kind: 'toon.stream-receipt-chain',
    v: STREAM_RECEIPT_VERSION,
    streamNonce: chain.streamNonce,
    totalDelivered: chain.totalDelivered,
    holes: chain.holes,
    receipts: chain.receipts.map((r) => ({
      v: r.v,
      streamNonce: r.streamNonce,
      seq: r.seq,
      cumulativeDelivered: r.cumulativeDelivered,
      rate: r.rate,
      rateTimestamp: r.rateTimestamp,
      sig: r.sig,
    })),
  });
}

// ---------------------------------------------------------------------------
// Maker-side session state — ReceiptSessionStore
// ---------------------------------------------------------------------------

/** Per-session receipt issuance state kept by the maker. */
export interface ReceiptSessionState {
  /** Last issued seq (0 = none issued yet). */
  seq: number;
  /** Cumulative asset-B delivered in the session so far (target micro-units). */
  cumulativeDelivered: bigint;
}

/**
 * Minimal synchronous store contract for maker-side receipt session state,
 * keyed by `streamNonce`.
 *
 * SYNCHRONOUS by design: the swap handler performs the read-increment-write
 * inside one microtask so concurrent packets in the same session get
 * distinct, gapless `seq` values and consistent cumulative totals. An
 * operator-supplied store that persists (e.g. alongside the claim/channel
 * store, so receipt state survives restarts like claims do) should
 * write-through asynchronously in the background while serving reads from
 * memory. The default is {@link BoundedReceiptSessions} (in-memory LRU).
 */
export interface ReceiptSessionStoreLike {
  get(streamNonce: string): ReceiptSessionState | undefined;
  set(streamNonce: string, state: ReceiptSessionState): unknown;
  delete(streamNonce: string): boolean;
}

/**
 * Default ceiling for the maker's receipt-session LRU. Same DoS rationale
 * as `DEFAULT_SEEN_PACKET_IDS_CAP`: bounds memory against an attacker
 * minting unlimited distinct stream nonces. An evicted (or maker-restarted)
 * session restarts at seq 1 — the sender's tracker then rejects the
 * duplicate seq loudly rather than accepting a forked chain.
 */
export const DEFAULT_RECEIPT_SESSIONS_CAP = 10_000;

/**
 * Bounded in-memory LRU {@link ReceiptSessionStoreLike}. Access-order
 * eviction: active sessions stay pinned while stale ones age out.
 */
export class BoundedReceiptSessions implements ReceiptSessionStoreLike {
  readonly #map = new Map<string, ReceiptSessionState>();
  readonly #cap: number;

  constructor(cap: number = DEFAULT_RECEIPT_SESSIONS_CAP) {
    if (!Number.isInteger(cap) || cap <= 0) {
      throw new Error(
        `BoundedReceiptSessions cap must be a positive integer, got ${cap}`
      );
    }
    this.#cap = cap;
  }

  get size(): number {
    return this.#map.size;
  }

  get cap(): number {
    return this.#cap;
  }

  get(streamNonce: string): ReceiptSessionState | undefined {
    const state = this.#map.get(streamNonce);
    if (state === undefined) return undefined;
    // Access-order promotion.
    this.#map.delete(streamNonce);
    this.#map.set(streamNonce, state);
    return state;
  }

  set(streamNonce: string, state: ReceiptSessionState): this {
    this.#map.delete(streamNonce);
    this.#map.set(streamNonce, state);
    while (this.#map.size > this.#cap) {
      const first = this.#map.keys().next();
      if (first.done) break;
      this.#map.delete(first.value);
    }
    return this;
  }

  delete(streamNonce: string): boolean {
    return this.#map.delete(streamNonce);
  }
}

/**
 * Maker-side: advance the session state for one fulfilled packet and issue
 * the corresponding signed receipt. The read-increment-write against the
 * store happens synchronously (no awaits) so concurrent handler invocations
 * interleave safely.
 *
 * MUST only be called for a packet that is being ACCEPTED — a rejected
 * packet gets no receipt and MUST NOT advance the session.
 */
export function issueSessionReceipt(input: {
  sessions: ReceiptSessionStoreLike;
  streamNonce: string;
  /** Asset-B amount delivered by THIS packet (target micro-units). */
  deliveredAmount: bigint;
  /** The quote-tape rate applied to this packet. */
  rate: string;
  /** The quote-tape timestamp for {@link rate}. */
  rateTimestamp: number;
  /** Maker receipt secret key (32-byte secp256k1). */
  secretKey: Uint8Array;
}): StreamReceipt {
  const { sessions, streamNonce, deliveredAmount, rate, rateTimestamp } = input;
  if (deliveredAmount < 0n) {
    throw new Error(
      `deliveredAmount must be non-negative, got ${deliveredAmount}`
    );
  }
  const prev = sessions.get(streamNonce) ?? {
    seq: 0,
    cumulativeDelivered: 0n,
  };
  const next: ReceiptSessionState = {
    seq: prev.seq + 1,
    cumulativeDelivered: prev.cumulativeDelivered + deliveredAmount,
  };
  const receipt = signStreamReceipt(
    {
      v: STREAM_RECEIPT_VERSION,
      streamNonce,
      seq: next.seq,
      cumulativeDelivered: next.cumulativeDelivered.toString(),
      rate,
      rateTimestamp,
    },
    input.secretKey
  );
  // Commit AFTER signing succeeds: a signing failure leaves the session
  // untouched so the packet can still be accepted receipt-less (or retried)
  // without burning a seq.
  sessions.set(streamNonce, next);
  return receipt;
}
