/**
 * Story 12.1 — SwapPair validation helper unit tests (ATDD RED PHASE).
 *
 * These tests are written BEFORE implementation (TDD red phase) and are
 * expected to FAIL until `packages/core/src/events/swap-pair-validation.ts`
 * is created with `isValidSwapPair`, `assertSwapPairForBuild`, and
 * `assertSwapPairForParse` per Task 2 in the story.
 *
 * Traceability:
 *   AC-5 (validation rules), AC-6 (error code), AC-8 (>= 8 helper tests)
 *   Risk: R-011 (backward-compat breakage), R-013 (BigInt precision)
 *
 * Generated by TEA ATDD workflow 2026-04-10.
 */

import { describe, it, expect } from 'vitest';
import {
  isValidSwapPair,
  assertSwapPairForBuild,
  assertSwapPairForParse,
} from './swap-pair-validation.js';
import { ToonError, InvalidEventError } from '../errors.js';
import type { SwapPair } from '../types.js';

// -----------------------------------------------------------------------------
// Test fixtures
// -----------------------------------------------------------------------------

function validPair(): SwapPair {
  return {
    from: { assetCode: 'USDC', assetScale: 6, chain: 'evm:base:8453' },
    to: { assetCode: 'ETH', assetScale: 18, chain: 'evm:base:8453' },
    rate: '0.00025',
    minAmount: '1000000',
    maxAmount: '1000000000',
  };
}

// -----------------------------------------------------------------------------
// isValidSwapPair — pure boolean-returning helper
// -----------------------------------------------------------------------------

describe('isValidSwapPair', () => {
  it('returns { valid: true } for a fully populated valid pair', () => {
    const result = isValidSwapPair(validPair());
    expect(result.valid).toBe(true);
  });

  it('returns { valid: true } when only rate and from/to are present (optional amounts omitted)', () => {
    const pair: SwapPair = {
      from: { assetCode: 'USDC', assetScale: 6, chain: 'mina:mainnet' },
      to: { assetCode: 'MINA', assetScale: 9, chain: 'mina:mainnet' },
      rate: '1.5',
    };
    const result = isValidSwapPair(pair);
    expect(result.valid).toBe(true);
  });

  it('accepts rate "0" (paused quoting) as valid', () => {
    const pair: SwapPair = { ...validPair(), rate: '0' };
    expect(isValidSwapPair(pair).valid).toBe(true);
  });

  it('accepts only-minAmount present (no maxAmount) as valid', () => {
    const pair: SwapPair = {
      ...validPair(),
      minAmount: '100',
      maxAmount: undefined,
    };
    expect(isValidSwapPair(pair).valid).toBe(true);
  });

  it('accepts only-maxAmount present (no minAmount) as valid', () => {
    const pair: SwapPair = {
      ...validPair(),
      minAmount: undefined,
      maxAmount: '999',
    };
    expect(isValidSwapPair(pair).valid).toBe(true);
  });

  // ---- invalid: missing top-level fields ----

  it('rejects null', () => {
    const result = isValidSwapPair(null);
    expect(result.valid).toBe(false);
  });

  it('rejects non-object input (string, number, array)', () => {
    expect(isValidSwapPair('not-a-pair').valid).toBe(false);
    expect(isValidSwapPair(42).valid).toBe(false);
    expect(isValidSwapPair([]).valid).toBe(false);
  });

  it('rejects when from is missing', () => {
    const bad = { ...validPair() } as unknown as Record<string, unknown>;
    delete bad['from'];
    const result = isValidSwapPair(bad);
    expect(result.valid).toBe(false);
    if (!result.valid) expect(result.field).toContain('from');
  });

  it('rejects when to is missing', () => {
    const bad = { ...validPair() } as unknown as Record<string, unknown>;
    delete bad['to'];
    const result = isValidSwapPair(bad);
    expect(result.valid).toBe(false);
    if (!result.valid) expect(result.field).toContain('to');
  });

  it('rejects when from is null', () => {
    const bad = { ...validPair(), from: null };
    expect(isValidSwapPair(bad).valid).toBe(false);
  });

  // ---- invalid: assetCode ----

  it('rejects empty from.assetCode', () => {
    const bad: SwapPair = {
      ...validPair(),
      from: { ...validPair().from, assetCode: '' },
    };
    const result = isValidSwapPair(bad);
    expect(result.valid).toBe(false);
    if (!result.valid) expect(result.field).toBe('from.assetCode');
  });

  it('rejects non-string to.assetCode', () => {
    const bad = {
      ...validPair(),
      to: { ...validPair().to, assetCode: 123 as unknown as string },
    };
    expect(isValidSwapPair(bad).valid).toBe(false);
  });

  // ---- invalid: assetScale ----

  it('rejects negative from.assetScale', () => {
    const bad: SwapPair = {
      ...validPair(),
      from: { ...validPair().from, assetScale: -1 },
    };
    const result = isValidSwapPair(bad);
    expect(result.valid).toBe(false);
    if (!result.valid) expect(result.field).toBe('from.assetScale');
  });

  it('rejects non-integer to.assetScale', () => {
    const bad: SwapPair = {
      ...validPair(),
      to: { ...validPair().to, assetScale: 6.5 },
    };
    expect(isValidSwapPair(bad).valid).toBe(false);
  });

  it('accepts assetScale === 0', () => {
    const pair: SwapPair = {
      ...validPair(),
      from: { ...validPair().from, assetScale: 0 },
    };
    expect(isValidSwapPair(pair).valid).toBe(true);
  });

  // ---- invalid: chain ----

  it('rejects malformed from.chain ("ethereum" with no colon)', () => {
    const bad: SwapPair = {
      ...validPair(),
      from: { ...validPair().from, chain: 'ethereum' },
    };
    const result = isValidSwapPair(bad);
    expect(result.valid).toBe(false);
    if (!result.valid) expect(result.field).toBe('from.chain');
  });

  it('rejects empty to.chain', () => {
    const bad: SwapPair = {
      ...validPair(),
      to: { ...validPair().to, chain: '' },
    };
    expect(isValidSwapPair(bad).valid).toBe(false);
  });

  it('rejects to.chain with 4 segments', () => {
    const bad: SwapPair = {
      ...validPair(),
      to: { ...validPair().to, chain: 'evm:base:8453:extra' },
    };
    expect(isValidSwapPair(bad).valid).toBe(false);
  });

  it('accepts 2-segment chain id (e.g. "mina:mainnet")', () => {
    const pair: SwapPair = {
      ...validPair(),
      from: { ...validPair().from, chain: 'mina:mainnet' },
      to: { ...validPair().to, chain: 'mina:mainnet' },
    };
    expect(isValidSwapPair(pair).valid).toBe(true);
  });

  // ---- invalid: rate ----

  it('rejects non-string rate (number)', () => {
    const bad = { ...validPair(), rate: 0.5 as unknown as string };
    expect(isValidSwapPair(bad).valid).toBe(false);
  });

  it('rejects rate in exponent notation ("1e5")', () => {
    const bad: SwapPair = { ...validPair(), rate: '1e5' };
    const result = isValidSwapPair(bad);
    expect(result.valid).toBe(false);
    if (!result.valid) expect(result.field).toBe('rate');
  });

  it('rejects rate with leading zero ("01.5")', () => {
    const bad: SwapPair = { ...validPair(), rate: '01.5' };
    expect(isValidSwapPair(bad).valid).toBe(false);
  });

  it('rejects negative rate ("-0.5")', () => {
    const bad: SwapPair = { ...validPair(), rate: '-0.5' };
    expect(isValidSwapPair(bad).valid).toBe(false);
  });

  it('rejects rate with trailing dot ("1.")', () => {
    const bad: SwapPair = { ...validPair(), rate: '1.' };
    expect(isValidSwapPair(bad).valid).toBe(false);
  });

  it('accepts high-precision rate ("0.000123456789012345")', () => {
    const pair: SwapPair = { ...validPair(), rate: '0.000123456789012345' };
    expect(isValidSwapPair(pair).valid).toBe(true);
  });

  // ---- invalid: minAmount / maxAmount ----

  it('rejects minAmount with decimal point ("1.5")', () => {
    const bad: SwapPair = { ...validPair(), minAmount: '1.5' };
    const result = isValidSwapPair(bad);
    expect(result.valid).toBe(false);
    if (!result.valid) expect(result.field).toBe('minAmount');
  });

  it('rejects negative maxAmount ("-100")', () => {
    const bad: SwapPair = { ...validPair(), maxAmount: '-100' };
    expect(isValidSwapPair(bad).valid).toBe(false);
  });

  it('rejects non-string maxAmount (number)', () => {
    const bad = { ...validPair(), maxAmount: 100 as unknown as string };
    expect(isValidSwapPair(bad).valid).toBe(false);
  });

  // ---- invalid: min > max (BigInt semantics) ----

  it('rejects minAmount > maxAmount using BigInt comparison', () => {
    const bad: SwapPair = {
      ...validPair(),
      minAmount: '1000',
      maxAmount: '500',
    };
    const result = isValidSwapPair(bad);
    expect(result.valid).toBe(false);
    if (!result.valid) expect(result.field).toMatch(/minAmount|maxAmount/);
  });

  it('rejects min > max for 20-digit values exceeding Number.MAX_SAFE_INTEGER', () => {
    const bad: SwapPair = {
      ...validPair(),
      minAmount: '99999999999999999999', // 20 digits
      maxAmount: '99999999999999999998', // 20 digits, one less
    };
    expect(isValidSwapPair(bad).valid).toBe(false);
  });

  it('accepts min === max (boundary)', () => {
    const pair: SwapPair = {
      ...validPair(),
      minAmount: '1000',
      maxAmount: '1000',
    };
    expect(isValidSwapPair(pair).valid).toBe(true);
  });

  it('accepts 20-digit maxAmount (beyond Number.MAX_SAFE_INTEGER)', () => {
    const pair: SwapPair = {
      ...validPair(),
      minAmount: '1',
      maxAmount: '99999999999999999999',
    };
    expect(isValidSwapPair(pair).valid).toBe(true);
  });

  // ---- security: BigInt DoS guards (wire-format input validation) ----

  it('rejects minAmount longer than 80 digits (BigInt DoS guard)', () => {
    const bad: SwapPair = {
      ...validPair(),
      minAmount: '1'.repeat(81),
      maxAmount: undefined,
    };
    const result = isValidSwapPair(bad);
    expect(result.valid).toBe(false);
    if (!result.valid) expect(result.field).toBe('minAmount');
  });

  it('rejects maxAmount longer than 80 digits (BigInt DoS guard)', () => {
    const bad: SwapPair = {
      ...validPair(),
      minAmount: undefined,
      maxAmount: '9'.repeat(81),
    };
    const result = isValidSwapPair(bad);
    expect(result.valid).toBe(false);
    if (!result.valid) expect(result.field).toBe('maxAmount');
  });

  it('rejects rate longer than 80 characters (regex/BigInt DoS guard)', () => {
    const bad: SwapPair = {
      ...validPair(),
      rate: '1'.repeat(50) + '.' + '2'.repeat(40),
    };
    const result = isValidSwapPair(bad);
    expect(result.valid).toBe(false);
    if (!result.valid) expect(result.field).toBe('rate');
  });

  it('accepts rate/amounts exactly at the 80-character boundary', () => {
    const pair: SwapPair = {
      ...validPair(),
      rate: '1'.repeat(80),
      minAmount: '1',
      maxAmount: '9'.repeat(80),
    };
    expect(isValidSwapPair(pair).valid).toBe(true);
  });
});

// -----------------------------------------------------------------------------
// assertSwapPairForBuild — builder-side throwing wrapper
// -----------------------------------------------------------------------------

describe('assertSwapPairForBuild', () => {
  it('does not throw on a valid pair', () => {
    expect(() => assertSwapPairForBuild(validPair(), 0)).not.toThrow();
  });

  it('throws ToonError with code INVALID_SWAP_PAIR on invalid pair', () => {
    const bad = { ...validPair(), rate: 'not-a-number' };
    expect(() => assertSwapPairForBuild(bad, 0)).toThrow(ToonError);
    try {
      assertSwapPairForBuild(bad, 0);
    } catch (e) {
      expect(e).toBeInstanceOf(ToonError);
      expect((e as ToonError).code).toBe('INVALID_SWAP_PAIR');
    }
  });

  it('includes swapPairs[index] and offending field in the error message', () => {
    const bad = { ...validPair(), rate: '-1' };
    try {
      assertSwapPairForBuild(bad, 3);
      expect.fail('should have thrown');
    } catch (e) {
      const msg = (e as Error).message;
      expect(msg).toContain('swapPairs[3]');
      expect(msg).toContain('rate');
    }
  });

  it('throws on invalid chain format', () => {
    const bad: SwapPair = {
      ...validPair(),
      from: { ...validPair().from, chain: 'bogus' },
    };
    expect(() => assertSwapPairForBuild(bad, 0)).toThrow(ToonError);
  });

  it('throws on min > max using BigInt comparison', () => {
    const bad: SwapPair = {
      ...validPair(),
      minAmount: '99999999999999999999',
      maxAmount: '1',
    };
    expect(() => assertSwapPairForBuild(bad, 0)).toThrow(
      /INVALID_SWAP_PAIR|swapPairs/
    );
  });
});

// -----------------------------------------------------------------------------
// assertSwapPairForParse — parser-side throwing wrapper
// -----------------------------------------------------------------------------

describe('assertSwapPairForParse', () => {
  it('does not throw on a valid pair', () => {
    expect(() => assertSwapPairForParse(validPair(), 0)).not.toThrow();
  });

  it('throws InvalidEventError (not ToonError base) on invalid pair', () => {
    const bad = { ...validPair(), rate: 123 as unknown as string };
    expect(() => assertSwapPairForParse(bad, 0)).toThrow(InvalidEventError);
  });

  it('includes swapPairs[index] and field in the error message', () => {
    const bad = { ...validPair() } as unknown as Record<string, unknown>;
    delete bad['to'];
    try {
      assertSwapPairForParse(bad, 7);
      expect.fail('should have thrown');
    } catch (e) {
      expect(e).toBeInstanceOf(InvalidEventError);
      const msg = (e as Error).message;
      expect(msg).toContain('swapPairs[7]');
      expect(msg).toContain('to');
    }
  });

  it('throws on empty assetCode', () => {
    const bad: SwapPair = {
      ...validPair(),
      from: { ...validPair().from, assetCode: '' },
    };
    expect(() => assertSwapPairForParse(bad, 0)).toThrow(InvalidEventError);
  });
});
